disabled_rules: # rule identifiers to exclude from running
  - trailing_newline
  - todo
  - valid_docs
opt_in_rules:
  - force_unwrapping
included:
  - KeyedMapper
line_length: 160
file_length:
  - 400 # warning
  - 500 # error
function_body_length:
  - 100 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
custom_rules:
  no_space_between_marks:
    name: "MARK usage"
    regex: "//\s+MARK"
    match_kinds:
      - comment
    message: "Don't place anything between the slashes and MARK"
    severity: error
