language: objective-c
osx_image: xcode8
rvm:
 - 2.3.0

before_install:
    - bundle install
    - bundle exec pod install

script:
 - xcodebuild clean build test -scheme KeyedMapper -sdk iphonesimulator -destination "id=9793E592-F0FF-4C4A-BEEF-FDD50A67E8C1" | xcpretty && exit ${PIPESTATUS[0]}
