language: swift
osx_image: xcode11.2
xcode_workspace: KeyedMapper.xcworkspace
xcode_scheme: KeyedMapper
xcode_destination: platform=iOS Simulator,OS=13.2.2,name=iPhone X
after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'KeyedMapper'
