language: objective-c
osx_image: xcode8
rvm:
    - 2.3.0
cache:
    - bundler
    - cocoapods

before_install:
    - brew tap Homebrew/bundle && brew bundle
    - bundle install
    - bundle exec pod install

script:
    - set -o pipefail && xcodebuild build-for-testing test-without-building -scheme KeyedMapper -workspace KeyedMapper.xcworkspace -sdk iphonesimulator -destination "name=iPhone SE" | xcpretty

after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'KeyedMapper'
