language: objective-c
osx_image: xcode8
rvm:
 - 2.3.0

before_install:
    - bundle install
    - bundle exec pod install

script:
 - xcodebuild build-for-testing test-without-building -scheme KeyedMapper -sdk iphonesimulator -destination "name=iPhone SE" | xcpretty && exit ${PIPESTATUS[0]}
