language: objective-c
osx_image: xcode8
rvm:
 - 2.3.0

before_install:
    - bundle install
    - bundle exec pod install

script:
 - xcodebuild clean build test -scheme KeyedMapper -sdk iphonesimulator | xcpretty && exit ${PIPESTATUS[0]}
