disabled_rules:
  - force_try
  - type_name
  - force_cast
  - mark
  - function_body_length
included:
  - KeyedMapper
  - KeyedMapperTests
line_length: 200
file_length:
  - 400 # warning
  - 500 # error
function_body_length:
  - 100 # warning
  - 200 # error
type_body_length:
  - 300 # warning
  - 400 # error
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
